// Jogos da fase de grupos em horário do Reino Unido (BST, UTC+1).
// O navegador exibe a hora no fuso local do usuário. O fechamento é calculado 5 minutos antes.
export const GROUP_FIXTURES = [
  {
    id: "match-001",
    matchNumber: 1,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "Mexico",
    teamB: "South Africa",
    teamACode: "MEX",
    teamBCode: "RSA",
    date: "2026-06-11T20:00:00+01:00",
    venue: "Mexico City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-002",
    matchNumber: 2,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "South Korea",
    teamB: "Czech Republic",
    teamACode: "KOR",
    teamBCode: "CZE",
    date: "2026-06-12T03:00:00+01:00",
    venue: "Zapopan",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-003",
    matchNumber: 3,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Canada",
    teamB: "Bosnia & Herzegovina",
    teamACode: "CAN",
    teamBCode: "BIH",
    date: "2026-06-12T20:00:00+01:00",
    venue: "Toronto",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-004",
    matchNumber: 4,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "USA",
    teamB: "Paraguay",
    teamACode: "USA",
    teamBCode: "PAR",
    date: "2026-06-13T02:00:00+01:00",
    venue: "Los Angeles",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-005",
    matchNumber: 5,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Qatar",
    teamB: "Switzerland",
    teamACode: "QAT",
    teamBCode: "SUI",
    date: "2026-06-13T20:00:00+01:00",
    venue: "Santa Clara",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-006",
    matchNumber: 6,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Brazil",
    teamB: "Morocco",
    teamACode: "BRA",
    teamBCode: "MAR",
    date: "2026-06-13T23:00:00+01:00",
    venue: "New Jersey",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-007",
    matchNumber: 7,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Haiti",
    teamB: "Scotland",
    teamACode: "HAI",
    teamBCode: "SCO",
    date: "2026-06-14T02:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-008",
    matchNumber: 8,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "Australia",
    teamB: "Turkey",
    teamACode: "AUS",
    teamBCode: "TUR",
    date: "2026-06-14T05:00:00+01:00",
    venue: "Vancouver",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-009",
    matchNumber: 9,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Germany",
    teamB: "Curacao",
    teamACode: "GER",
    teamBCode: "CUW",
    date: "2026-06-14T18:00:00+01:00",
    venue: "Houston",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-010",
    matchNumber: 10,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Netherlands",
    teamB: "Japan",
    teamACode: "NED",
    teamBCode: "JPN",
    date: "2026-06-14T21:00:00+01:00",
    venue: "Arlington",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-011",
    matchNumber: 11,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Ivory Coast",
    teamB: "Ecuador",
    teamACode: "CIV",
    teamBCode: "ECU",
    date: "2026-06-15T00:00:00+01:00",
    venue: "Philadelphia",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-012",
    matchNumber: 12,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Sweden",
    teamB: "Tunisia",
    teamACode: "SWE",
    teamBCode: "TUN",
    date: "2026-06-15T03:00:00+01:00",
    venue: "Guadalupe",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-013",
    matchNumber: 13,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Spain",
    teamB: "Cape Verde",
    teamACode: "ESP",
    teamBCode: "CPV",
    date: "2026-06-15T17:00:00+01:00",
    venue: "Atlanta",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-014",
    matchNumber: 14,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "Belgium",
    teamB: "Egypt",
    teamACode: "BEL",
    teamBCode: "EGY",
    date: "2026-06-15T20:00:00+01:00",
    venue: "Seattle",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-015",
    matchNumber: 15,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Saudi Arabia",
    teamB: "Uruguay",
    teamACode: "KSA",
    teamBCode: "URU",
    date: "2026-06-15T23:00:00+01:00",
    venue: "Miami",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-016",
    matchNumber: 16,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "Iran",
    teamB: "New Zealand",
    teamACode: "IRN",
    teamBCode: "NZL",
    date: "2026-06-16T02:00:00+01:00",
    venue: "Los Angeles",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-017",
    matchNumber: 17,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "France",
    teamB: "Senegal",
    teamACode: "FRA",
    teamBCode: "SEN",
    date: "2026-06-16T20:00:00+01:00",
    venue: "New Jersey",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-018",
    matchNumber: 18,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "Iraq",
    teamB: "Norway",
    teamACode: "IRQ",
    teamBCode: "NOR",
    date: "2026-06-16T23:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-019",
    matchNumber: 19,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Argentina",
    teamB: "Algeria",
    teamACode: "ARG",
    teamBCode: "ALG",
    date: "2026-06-17T02:00:00+01:00",
    venue: "Kansas City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-020",
    matchNumber: 20,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Austria",
    teamB: "Jordan",
    teamACode: "AUT",
    teamBCode: "JOR",
    date: "2026-06-17T05:00:00+01:00",
    venue: "Santa Clara",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-021",
    matchNumber: 21,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "Portugal",
    teamB: "DR Congo",
    teamACode: "POR",
    teamBCode: "COD",
    date: "2026-06-17T18:00:00+01:00",
    venue: "Houston",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-022",
    matchNumber: 22,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "England",
    teamB: "Croatia",
    teamACode: "ENG",
    teamBCode: "CRO",
    date: "2026-06-17T21:00:00+01:00",
    venue: "Arlington",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-023",
    matchNumber: 23,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "Ghana",
    teamB: "Panama",
    teamACode: "GHA",
    teamBCode: "PAN",
    date: "2026-06-18T00:00:00+01:00",
    venue: "Toronto",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-024",
    matchNumber: 24,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "Uzbekistan",
    teamB: "Colombia",
    teamACode: "UZB",
    teamBCode: "COL",
    date: "2026-06-18T03:00:00+01:00",
    venue: "Mexico City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-025",
    matchNumber: 25,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "Czech Republic",
    teamB: "South Africa",
    teamACode: "CZE",
    teamBCode: "RSA",
    date: "2026-06-18T17:00:00+01:00",
    venue: "Atlanta",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-026",
    matchNumber: 26,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Switzerland",
    teamB: "Bosnia & Herzegovina",
    teamACode: "SUI",
    teamBCode: "BIH",
    date: "2026-06-18T20:00:00+01:00",
    venue: "Los Angeles",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-027",
    matchNumber: 27,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Canada",
    teamB: "Qatar",
    teamACode: "CAN",
    teamBCode: "QAT",
    date: "2026-06-18T23:00:00+01:00",
    venue: "Vancouver",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-028",
    matchNumber: 28,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "Mexico",
    teamB: "South Korea",
    teamACode: "MEX",
    teamBCode: "KOR",
    date: "2026-06-19T02:00:00+01:00",
    venue: "Zapopan",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-029",
    matchNumber: 29,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "USA",
    teamB: "Australia",
    teamACode: "USA",
    teamBCode: "AUS",
    date: "2026-06-19T20:00:00+01:00",
    venue: "Seattle",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-030",
    matchNumber: 30,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Scotland",
    teamB: "Morocco",
    teamACode: "SCO",
    teamBCode: "MAR",
    date: "2026-06-19T23:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-031",
    matchNumber: 31,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Brazil",
    teamB: "Haiti",
    teamACode: "BRA",
    teamBCode: "HAI",
    date: "2026-06-20T01:30:00+01:00",
    venue: "Philadelphia",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-032",
    matchNumber: 32,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "Turkey",
    teamB: "Paraguay",
    teamACode: "TUR",
    teamBCode: "PAR",
    date: "2026-06-20T04:00:00+01:00",
    venue: "Santa Clara",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-033",
    matchNumber: 33,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Netherlands",
    teamB: "Sweden",
    teamACode: "NED",
    teamBCode: "SWE",
    date: "2026-06-20T18:00:00+01:00",
    venue: "Houston",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-034",
    matchNumber: 34,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Germany",
    teamB: "Ivory Coast",
    teamACode: "GER",
    teamBCode: "CIV",
    date: "2026-06-20T21:00:00+01:00",
    venue: "Toronto",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-035",
    matchNumber: 35,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Ecuador",
    teamB: "Curacao",
    teamACode: "ECU",
    teamBCode: "CUW",
    date: "2026-06-21T01:00:00+01:00",
    venue: "Kansas City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-036",
    matchNumber: 36,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Tunisia",
    teamB: "Japan",
    teamACode: "TUN",
    teamBCode: "JPN",
    date: "2026-06-21T05:00:00+01:00",
    venue: "Guadalupe",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-037",
    matchNumber: 37,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Spain",
    teamB: "Saudi Arabia",
    teamACode: "ESP",
    teamBCode: "KSA",
    date: "2026-06-21T17:00:00+01:00",
    venue: "Atlanta",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-038",
    matchNumber: 38,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "Belgium",
    teamB: "Iran",
    teamACode: "BEL",
    teamBCode: "IRN",
    date: "2026-06-21T20:00:00+01:00",
    venue: "Los Angeles",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-039",
    matchNumber: 39,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Uruguay",
    teamB: "Cape Verde",
    teamACode: "URU",
    teamBCode: "CPV",
    date: "2026-06-21T23:00:00+01:00",
    venue: "Miami",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-040",
    matchNumber: 40,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "New Zealand",
    teamB: "Egypt",
    teamACode: "NZL",
    teamBCode: "EGY",
    date: "2026-06-22T02:00:00+01:00",
    venue: "Vancouver",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-041",
    matchNumber: 41,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Argentina",
    teamB: "Austria",
    teamACode: "ARG",
    teamBCode: "AUT",
    date: "2026-06-22T18:00:00+01:00",
    venue: "Arlington",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-042",
    matchNumber: 42,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "France",
    teamB: "Iraq",
    teamACode: "FRA",
    teamBCode: "IRQ",
    date: "2026-06-22T22:00:00+01:00",
    venue: "Philadelphia",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-043",
    matchNumber: 43,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "Norway",
    teamB: "Senegal",
    teamACode: "NOR",
    teamBCode: "SEN",
    date: "2026-06-23T01:00:00+01:00",
    venue: "Toronto",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-044",
    matchNumber: 44,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Jordan",
    teamB: "Algeria",
    teamACode: "JOR",
    teamBCode: "ALG",
    date: "2026-06-23T04:00:00+01:00",
    venue: "Santa Clara",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-045",
    matchNumber: 45,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "Portugal",
    teamB: "Uzbekistan",
    teamACode: "POR",
    teamBCode: "UZB",
    date: "2026-06-23T18:00:00+01:00",
    venue: "Houston",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-046",
    matchNumber: 46,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "England",
    teamB: "Ghana",
    teamACode: "ENG",
    teamBCode: "GHA",
    date: "2026-06-23T21:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-047",
    matchNumber: 47,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "Panama",
    teamB: "Croatia",
    teamACode: "PAN",
    teamBCode: "CRO",
    date: "2026-06-24T00:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-048",
    matchNumber: 48,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "Colombia",
    teamB: "DR Congo",
    teamACode: "COL",
    teamBCode: "COD",
    date: "2026-06-24T03:00:00+01:00",
    venue: "Zapopan",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-049",
    matchNumber: 49,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Switzerland",
    teamB: "Canada",
    teamACode: "SUI",
    teamBCode: "CAN",
    date: "2026-06-24T20:00:00+01:00",
    venue: "Vancouver",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-050",
    matchNumber: 50,
    phase: "Grupo B",
    phaseType: "group",
    teamA: "Bosnia & Herzegovina",
    teamB: "Qatar",
    teamACode: "BIH",
    teamBCode: "QAT",
    date: "2026-06-24T20:00:00+01:00",
    venue: "Seattle",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-051",
    matchNumber: 51,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Morocco",
    teamB: "Haiti",
    teamACode: "MAR",
    teamBCode: "HAI",
    date: "2026-06-24T23:00:00+01:00",
    venue: "Atlanta",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-052",
    matchNumber: 52,
    phase: "Grupo C",
    phaseType: "group",
    teamA: "Scotland",
    teamB: "Brazil",
    teamACode: "SCO",
    teamBCode: "BRA",
    date: "2026-06-24T23:00:00+01:00",
    venue: "Miami",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-053",
    matchNumber: 53,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "South Africa",
    teamB: "South Korea",
    teamACode: "RSA",
    teamBCode: "KOR",
    date: "2026-06-25T02:00:00+01:00",
    venue: "Guadalupe",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-054",
    matchNumber: 54,
    phase: "Grupo A",
    phaseType: "group",
    teamA: "Czech Republic",
    teamB: "Mexico",
    teamACode: "CZE",
    teamBCode: "MEX",
    date: "2026-06-25T02:00:00+01:00",
    venue: "Mexico City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-055",
    matchNumber: 55,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Curacao",
    teamB: "Ivory Coast",
    teamACode: "CUW",
    teamBCode: "CIV",
    date: "2026-06-25T21:00:00+01:00",
    venue: "Philadelphia",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-056",
    matchNumber: 56,
    phase: "Grupo E",
    phaseType: "group",
    teamA: "Ecuador",
    teamB: "Germany",
    teamACode: "ECU",
    teamBCode: "GER",
    date: "2026-06-25T21:00:00+01:00",
    venue: "New Jersey",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-057",
    matchNumber: 57,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Tunisia",
    teamB: "Netherlands",
    teamACode: "TUN",
    teamBCode: "NED",
    date: "2026-06-26T00:00:00+01:00",
    venue: "Kansas City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-058",
    matchNumber: 58,
    phase: "Grupo F",
    phaseType: "group",
    teamA: "Japan",
    teamB: "Sweden",
    teamACode: "JPN",
    teamBCode: "SWE",
    date: "2026-06-26T00:00:00+01:00",
    venue: "Arlington",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-059",
    matchNumber: 59,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "Turkey",
    teamB: "USA",
    teamACode: "TUR",
    teamBCode: "USA",
    date: "2026-06-26T03:00:00+01:00",
    venue: "Los Angeles",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-060",
    matchNumber: 60,
    phase: "Grupo D",
    phaseType: "group",
    teamA: "Paraguay",
    teamB: "Australia",
    teamACode: "PAR",
    teamBCode: "AUS",
    date: "2026-06-26T03:00:00+01:00",
    venue: "Santa Clara",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-061",
    matchNumber: 61,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "Norway",
    teamB: "France",
    teamACode: "NOR",
    teamBCode: "FRA",
    date: "2026-06-26T20:00:00+01:00",
    venue: "Foxborough",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-062",
    matchNumber: 62,
    phase: "Grupo I",
    phaseType: "group",
    teamA: "Senegal",
    teamB: "Iraq",
    teamACode: "SEN",
    teamBCode: "IRQ",
    date: "2026-06-26T20:00:00+01:00",
    venue: "Toronto",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-063",
    matchNumber: 63,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Cape Verde",
    teamB: "Saudi Arabia",
    teamACode: "CPV",
    teamBCode: "KSA",
    date: "2026-06-27T01:00:00+01:00",
    venue: "Houston",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-064",
    matchNumber: 64,
    phase: "Grupo H",
    phaseType: "group",
    teamA: "Uruguay",
    teamB: "Spain",
    teamACode: "URU",
    teamBCode: "ESP",
    date: "2026-06-27T01:00:00+01:00",
    venue: "Zapopan",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-065",
    matchNumber: 65,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "New Zealand",
    teamB: "Belgium",
    teamACode: "NZL",
    teamBCode: "BEL",
    date: "2026-06-27T04:00:00+01:00",
    venue: "Vancouver",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-066",
    matchNumber: 66,
    phase: "Grupo G",
    phaseType: "group",
    teamA: "Egypt",
    teamB: "Iran",
    teamACode: "EGY",
    teamBCode: "IRN",
    date: "2026-06-27T04:00:00+01:00",
    venue: "Seattle",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-067",
    matchNumber: 67,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "Panama",
    teamB: "England",
    teamACode: "PAN",
    teamBCode: "ENG",
    date: "2026-06-27T22:00:00+01:00",
    venue: "New Jersey",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-068",
    matchNumber: 68,
    phase: "Grupo L",
    phaseType: "group",
    teamA: "Croatia",
    teamB: "Ghana",
    teamACode: "CRO",
    teamBCode: "GHA",
    date: "2026-06-27T22:00:00+01:00",
    venue: "Philadelphia",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-069",
    matchNumber: 69,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "Colombia",
    teamB: "Portugal",
    teamACode: "COL",
    teamBCode: "POR",
    date: "2026-06-28T00:30:00+01:00",
    venue: "Miami",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-070",
    matchNumber: 70,
    phase: "Grupo K",
    phaseType: "group",
    teamA: "DR Congo",
    teamB: "Uzbekistan",
    teamACode: "COD",
    teamBCode: "UZB",
    date: "2026-06-28T00:30:00+01:00",
    venue: "Atlanta",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-071",
    matchNumber: 71,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Algeria",
    teamB: "Austria",
    teamACode: "ALG",
    teamBCode: "AUT",
    date: "2026-06-28T03:00:00+01:00",
    venue: "Kansas City",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  },
  {
    id: "match-072",
    matchNumber: 72,
    phase: "Grupo J",
    phaseType: "group",
    teamA: "Jordan",
    teamB: "Argentina",
    teamACode: "JOR",
    teamBCode: "ARG",
    date: "2026-06-28T03:00:00+01:00",
    venue: "Arlington",
    status: "open",
    scoreA: null,
    scoreB: null,
    allowPenalties: false,
    penaltyWinner: null
  }
];
